#!/bin/bash

trap "echo Exited!; exit;" SIGINT SIGTERM

while true; do
  ag -g '\.rb$' | entr -c -d -p -s 'bundle exec rubocop -A english_number.rb; bundle exec reek english_number.rb; bundle exec ruby *_test.rb'
done
